name = "icak-interest-api"
main = "interest-worker.js"
compatibility_date = "2026-06-18"

# Required binding name: DB
[[d1_databases]]
binding = "DB"
database_name = "icak-interest-db"
database_id = "a4589c64-e837-4319-8791-f2bfedc81f88"
